#ifndef MENOH_IMPL_MKLDNN_WITH_GENERIC_FALLBACK_BACKEND_GENERIC_OPERATOR_HPP
#define MENOH_IMPL_MKLDNN_WITH_GENERIC_FALLBACK_BACKEND_GENERIC_OPERATOR_HPP

#include <menoh/mkldnn_with_generic_fallback/backend/generic/operator/relu.hpp>
#include <menoh/mkldnn_with_generic_fallback/backend/generic/operator/mul.hpp>
#include <menoh/mkldnn_with_generic_fallback/backend/generic/operator/sigmoid.hpp>

#endif // MENOH_IMPL_MKLDNN_WITH_GENERIC_FALLBACK_BACKEND_GENERIC_OPERATOR_HPP
